### ISSUE TITLE
How is the work you do different from go-ftw?

### ISSUE THREAD

**Issue by Axkea** [dextermallo/GSoC-2023#12]
I am currently using go-ftw for rule set testing, if your testing framework is more efficient. I'd like to consider using your framework

**Comment by dexter-ys** [comment]
Hi @Axkea, this repository primarily evaluates "performance" regarding CRS. 

The original purpose [(ref)](https://github.com/dextermallo/GSoC-2023#introduction) is to estimate the potential performance when a rule is updated. For instance, you may have a rule like:

```sh
SecRule REQUEST_METHOD "@rx ^(?:GET|HEAD)$" \
```

And you are curious about whether the performance will be affected by this change:
```sh
# A very large regex
SecRule REQUEST_METHOD "@rx ^(?:dog|jump|tree|jump|jump|dance|dance|.......|hidebright|bright|GET|HEAD)$" \
```

In this case, using the framework can help you to get the statistics.

e.g., statistics from `go-ftw` (focus on test case changes)

<img width="1100" alt="image" src="https://github.com/dextermallo/GSoC-2023/assets/29012607/1d61252f-c054-406b-a72b-b469f5f83d36">


statistics from `cAdvisor` (focus on resource utilisation changes)

<img width="1377" alt="image" src="https://github.com/dextermallo/GSoC-2023/assets/29012607/b36f6ca6-d613-4236-a7d0-e4e989657bad">


statistics from `locust` (focus on load testing changes)

<img width="1377" alt="image" src="https://github.com/dextermallo/GSoC-2023/assets/29012607/85c75fc6-8c70-4026-9554-fa9f21bed715">

As for testing the functionality, go-ftw is currently much more efficient than the framework.

**Comment by Axkea** [comment]
I know the difference between the two. Thank you for your patience.By the way, are you Chinese?

**Comment by dexter-ys** [comment]
> I know the difference between the two. Thank you for your patience.By the way, are you Chinese?

Welcome! I am from Taiwan. If you have further questions aside from the repo, feel free to ping me on Linkedin or OWSAP Slack channel :)
