### ISSUE TITLE
Research on Low-level matrices

### ISSUE THREAD

**Issue by dextermallo** [dextermallo/GSoC-2023#5]
Research on low-level matrices. (e.g., from syscall, kernel, packets)

**Comment by dexter-ys** [comment]
Some literature review:
- [Performance Analysis and Optimization of Nginx-based Web Server](https://iopscience.iop.org/article/10.1088/1742-6596/1955/1/012033/meta)
  - Utils: [jMeter](https://jmeter.apache.org/), [Nmon](https://nmon.sourceforge.net/pmwiki.php)
  - Matrices: throughput; receive/send; response time; 90% response time; memory available
- [Comparison Analysis of Apache and Nginx Webserver Load Balancing on Proxmox VE in Supporting Server Performance](http://irjaes.com/wp-content/uploads/2022/08/[IRJAES-V7N3P161Y22.pdf](http://irjaes.com/wp-content/uploads/2022/08/IRJAES-V7N3P161Y22.pdf))
  - Utils: [Loader.io](https://loader.io/)
  - Matrices: response time
- [Web Server Performance Modeling](https://link.springer.com/article/10.1023/A:1016667027983)
  - Matrices: RTT, transactions/sec, server throughput, response time

**Comment by dexter-ys** [comment]
Another thought: analysis syscall

attempt (failed): blocked by System Integrity Protection (SIP) on Mac
<img width="1552" alt="image" src="https://github.com/dextermallo/GSoC-2023/assets/29012607/df4c052e-a23e-4d26-abf1-15edeaa1e9ce">

Ref: [Using dtrace on MacOS with SIP enabled | by Chris | poweruser.blog](https://poweruser.blog/using-dtrace-with-sip-enabled-3826a352e64b)

**Comment by dexter-ys** [comment]
TBD: [sysdig](https://github.com/draios/sysdig)

**Comment by dexter-ys** [comment]
Updated in #3 and the latest update in README.
