### ISSUE TITLE
WIP: Concerns about Cache for performance evaluation

### ISSUE THREAD

**Issue by dextermallo** [dextermallo/GSoC-2023#7]
Cached requests are a concern when performing the test. While it is not the most urgent task at the moment, I just partially reviewed the cache mechanism in both ModSecurity (v2.9+ and v3.0+) and Coraza.

Coraza: 
ModSec:

**Comment by dune73** [comment]
Is there any chaching implemented in ModSec 2.9? If yes, I was not aware of it.

FYI: There used to be caching for transformation during the 2.5.x release line but it was quickly removed due to security concerns.

**Comment by dexter-ys** [comment]
> Is there any chaching implemented in ModSec 2.9? If yes, I was not aware of it.
> 
> FYI: There used to be caching for transformation during the 2.5.x release line but it was quickly removed due to security concerns.

I was doing the experiment back then. I think the ticket can be closed while the current design is more focused on the implementation with other utils (eBPF, locust, go-ftw, etc.) 👍
